#
# micronaut application config
#

micronaut:
  application:
    name: microhipstering-demo

  heartbeat:
    enabled:    true
    interval:   PT5S

  executors:
    io:
      type:                   scheduled
      core-pool-size:         1
      n-threads:              50

  server:
    netty:
      validate-headers:       false
      use-native-transport:   true
      compression-threshold:  512
      log-level: debug

# biz-logic stuff
services:
  query:
    min-delay: 5
    max-delay: 23

# vim:shiftwidth=2 softtabstop=2 expandtab
# EOF
